services:
  - type: web
    name: food-analyzer-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: OPENAI_API_KEY
        sync: false
    domains:
      - snap-food.onrender.com
      - deepseek-uhrc.onrender.com 